# Generated by Django 4.1.5 on 2023-01-17 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_task_donde'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='donde',
            new_name='done',
        ),
    ]
